property: "(G(
              ![inSeven==0] & ![inEight==0] & [inEight-inSeven>20] & [inSeven>=-1] & [inSeven<=50] & [inEight>=-1] & [inEight<=50]
            )
            -> G(
              [vEight == inEight + inSeven]
            ))
          &
          (G(
              ([inTen>=0] & [inSeven<=100]) & ([inEleven>=0] & [inEleven<=100])
            )
            -> G(
              ([vFour==inTen] | [vFour==1]) & ([vFive==inEleven] | [vFive==1])
            ))
          &
          (G(
              ([inTen>=0] & [inSeven<=100]) & ([inEleven>=0] & [inEleven<=100])
            )
            -> G(
              ([vFour==inTen] | [vFour==1])
            ))"
variables:
  - name: vEight
    type: Int
    owner: system
  - name: inEight
    type: Int
    owner: environment
  - name: inSeven
    type: Int
    owner: environment
  - name: vFour
    type: Int
    owner: system
  - name: vFive
    type: Int
    owner: environment
  - name: inTen
    type: Int
    owner: environment
  - name: inSeven
    type: Int
    owner: environment
  - name: inEleven
    type: Int
    owner: environment