property: "MANY"
property: "G(
              ([inOne > 1] | [inOne<= frac*2]) & ([inOne>=0] & [inOne<=200])
            )
            &
            G(
              [vTen==100] & [vSix==100]
            )
            &
            G(
              [vSeven==100] | [vSeven==100*frac] | [vSeven==2*dfrac]
            )
            &
            G(
              [vTwo==1]
            )
          &
          (G(
              ![inSeven==0] & ![inEight==0] & [inEight-inSeven>20] & [inSeven>=-1] & [inSeven<=50] & [inEight>=-1] & [inEight<=50]
            )
            -> G(
              [vEight == inEight + inSeven]
            ))
          &
          (G(
              ([inTen>=0] & [inSeven<=100]) & ([inEleven>=0] & [inEleven<=100])
            )
            -> G(
              ([vFour==inTen] | [vFour==1]) & ([vFive==inEleven] | [vFive==1])
            ))
          &
          (G(
              ([inTen>=0] & [inSeven<=100]) & ([inEleven>=0] & [inEleven<=100])
            )
            -> G(
              ([vFour==inTen] | [vFour==1])
            ))
          &
          G(
              [vFourteen>vTwelve] & [vThirtheen > vTwelve] & ([vTwelve>0] | [vTwelve<frac*dfrac])
              & [vFifteen > 10] & [vFifteen == vThirtheen] & [vThirtheen==0]
              & [vTwelve > vFifteen] & [vFourteen == vFifteen] & [vTwelve>=0]
              & ![vFourteen == vTwelve] & [vThirtheen*frac>vTwelve]
            )
            "
variables:
  - name: frac
    type: Int
    owner: system
  - name: inOne
    type: Int
    owner: environment
  - name: vSix
    type: Int
    owner: system
  - name: vTen
    type: Int
    owner: system
  - name: vSeven
    type: Int
    owner: system
  - name: frac
    type: Int
    owner: system
  - name: dfrac
    type: Int
    owner: system
  - name: vTwo
    type: Int
    owner: system
  - name: vEight
    type: Int
    owner: system
  - name: inEight
    type: Int
    owner: environment
  - name: inSeven
    type: Int
    owner: environment
  - name: vFour
    type: Int
    owner: system
  - name: vFive
    type: Int
    owner: environment
  - name: inTen
    type: Int
    owner: environment
  - name: inSeven
    type: Int
    owner: environment
  - name: inEleven
    type: Int
    owner: environment
  - name: vFourteen
    type: Int
    owner: system
  - name: vThirtheen
    type: Int
    owner: system
  - name: vFifteen
    type: Int
    owner: system
  - name: vTwelve
    type: Int
    owner: system

